#!/bin/bash
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [[ $TERMINIX_ID ]]; then
  source /etc/profile.d/vte*
fi

export TDS="$HOME/.cache/TheDarkSide"
export PATH="/var/tmp/cmake/bin:$TDS/bin:$HOME/.local/bin:$PATH"
export LD_LIBRARY_PATH="/var/tmp/sfml/lib:/var/tmp/boost-install/lib:$LD_LIBRARY_PATH"

function atom {
  local PWD
  export PWD="$TDS/atom"
  "$TDS"/atom/atom
}

function tmux {
  "$TDS"/tmux -S /tmp/tmux "$@"
  chmod 777 /tmp/tmux
}
tmux new -d -s TheDarkSide 2>/dev/null

alias dconf="$TDS/dconf"
alias terminix="$TDS/terminix.bash"
alias apm="$TDS/atom/resources/app/apm/bin/apm"

alias mouse-click="xfconf-query -n -c xfwm4 -p /general/click_to_focus -t bool -s true"
alias mouse-unclick="xfconf-query -n -c xfwm4 -p /general/click_to_focus -t bool -s false"

alias TDS-check-version="$TDS/check-version.bash"
alias TDS-update="$TDS/update.bash"
alias TDS-volume="$TDS/volume.bash"
alias TDS-install-add-on="$TDS/install-add-on.bash"

export BASH_IT="$HOME/.cache/TheDarkSide/bash_it"
export BASH_IT_THEME='powerline-multiline'
export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=''
unset MAILCHECK
export SCM_CHECK=true
export SCM_GIT_SHOW_DETAILS=true
export EDITOR="gedit -s"
export SVN_EDITOR="gedit -s"
source "$BASH_IT/bash_it.sh"

complete -d cd
