#!/bin/bash
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [[ $TERMINIX_ID ]]; then
  source /etc/profile.d/vte.sh
fi

function tmux {
  ~/.cache/TheDarkSide/tmux -S /tmp/tmux "$@"
  chmod 777 /tmp/tmux
}
tmux new -d -s TheDarkSide 2>/dev/null

alias dconf=~/.cache/TheDarkSide/dconf
alias terminix=~/.cache/TheDarkSide/terminix.bash
alias apm=~/.cache/TheDarkSide/atom/resources/app/apm/bin/apm

export BASH_IT="$HOME/.cache/TheDarkSide/bash_it"
export BASH_IT_THEME='powerline-multiline'
export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=''
unset MAILCHECK
export SCM_CHECK=true
export SCM_GIT_SHOW_DETAILS=true
export EDITOR=vim
source "$BASH_IT/bash_it.sh"

complete -d cd
