language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt59base qt59quickcontrols2
    - source /opt/qt*/bin/qt*-env.sh

script:
  - qmake PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir install ; find appdir/

after_success:
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs -qmldir=qml
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
  - chmod a+x appimagetool-x86_64.AppImage
  - APPIMAGE="./TheDarkSide-$(git rev-parse --abbrev-ref HEAD)-x86_64.AppImage"
  - ./appimagetool-x86_64.AppImage --updateinformation --bintray-user $BINTRAY_USER --bintray-repo $BINTRAY_REPO --no-appstream --verbose ./appdir "$APPIMAGE"
  - wget https://raw.githubusercontent.com/probonopd/AppImages/master/bintray.sh
  - chmod a+x ./bintray.sh
  - ./bintray.sh "$APPIMAGE" || exit 1
