disable atom-bootstrap3
disable atom-html-preview
enable atom-monokai
disable build
disable build-cmake
disable build-make
enable busy
enable busy-signal
enable color-picker
enable data-atom
enable file-icons
enable flex-tool-bar
enable git-plus
enable highlight-selected
enable intentions
disable language-cmake
disable language-doxygen
enable language-pgsql
disable language-x86-64-assembly
enable linter
disable linter-csslint
disable linter-gcc
disable linter-htmlhint
enable linter-shellcheck
enable linter-stylelint
enable linter-ui-default
enable merge-conflicts
enable minimap
enable minimap-bookmarks
enable minimap-cursorline
enable minimap-find-and-replace
enable minimap-git-diff
enable minimap-highlight-selected
enable minimap-linter
enable minimap-pigments
enable minimap-selection
enable minimap-split-diff
enable northem-dark-atom-ui
enable open-recent
enable open-terminal-here
enable pigments
enable random
disable scilab-language
enable script
enable simple-drag-drop-text
enable split-diff
enable svn
enable switch-header-source
enable tool-bar
enable tree-view-autoresize
enable tree-view-git-status
